//Teste de Requisições REST - Prestadores
//@baseURL = https://backdogwalker.herokuapp.com/api
@baseURL = http://localhost:4000/api
@id = 6267f34532ae23b306a82e20
@razao = capura
###
// GET - Lista todos os prestadores
GET {{baseURL}}/prestadores
Content-Type: application/json

###
// GET - Lista apenas um prestador pelo id
GET {{baseURL}}/prestadores/id/{{id}}
Content-Type: application/json

###
// GET - Lista apenas um prestador pela razão social
GET {{baseURL}}/prestadores/razao/{{razao}}
Content-Type: application/json

###
// POST - Inclui um novo prestador
POST {{baseURL}}/prestadores
Content-Type: application/json

c

### 
// DELETE - Apaga um prestador através do id informado
DELETE {{baseURL}}/prestadores/{{id}}
Content-Type: application/json

###
// PUT - Altera um prestador pelo ID
PUT {{baseURL}}/prestadores
Content-Type: application/json

{
   "_id": "6267f34532ae23b306a82e20",
   "nome": "Pedro",
   "email": "pedro@gmail.com",
   "celular": "1233321313",
   "servico": "Pintor",
   "obs": "Caprichoso",
   "ativo": "",
}



